### ISSUE TITLE
Add jetpack navigation

### ISSUE THREAD

**Issue by Canato** [Canato/Purity-Test#50]
Create a new domain: **home**

Home will be responsible to navigate to login and question using jetpack navigation 

example code: https://github.com/canato/showcase

**Comment by tomklecha** [comment]
@Canato question about AC for this feature.
I achieved the navigation between all 3 fragments - but home fragment for now have navigation like -   loginButton.setOnClickListener {
            findNavController().navigate(R.id.action_go_to_login)
        }

do you expect ENUM for navigationId ?

**Comment by Canato** [comment]
@tomklecha can you be clear? 

there is not navigationId in you code, don't know where or what are you talking about. 

Please when putting code use ```
```
code
```
So is easy to read.


What is the problem that you are facing or the question exactly?
