### ISSUE TITLE
Add Firebase Auth in Login Data Layer

### ISSUE THREAD

**Issue by Canato** [Canato/Purity-Test#6]
**Acceptance Criteria:**
- Have the e-mail and password check in Firebase Authenticator;
- If user don't exist, try to create;

**Documentation:** https://firebase.google.com/docs/auth

**Comment by tomklecha** [comment]
Hi @Canato question, should i create the Firebase authenticator in my login module ? or in main app module ?
Because i dont have the firebase line in my build.gradle file, so for now i dont know in which module to implement

**Comment by tomklecha** [comment]
I am bit confused now. In #10 i have resolve #6 and #6 is showing that might resolve #10.
Because i dont know what i should pull or fix. I am sorry for that.

**Comment by Canato** [comment]
10 is a pull request
6 is a issue

the pull request(10) resolve this issue(6). So when 10 is done, 6 is resolved.

`6 is showing that might resolve 10` 
where you saw this?

**Comment by tomklecha** [comment]
Its on top #6 might be fixed by #10.

Ok. Now i got it. Your comment "resolve #6" means - that pull will resolve #6, not @tomklecha resolve #6 before doing merge on #10.
By bad, everyday learning something new :)

**Comment by tomklecha** [comment]
@Canato after giving valid password and login, this is the exception going from FirebaseAuth:
The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.
