### ISSUE TITLE
Jetpack Compose implementation

### ISSUE THREAD

**Issue by lucasvillaverde** [Canato/Purity-Test#62]
In order to keep in touch with new technologies and follow Google's new app architecture guideline, i would suggest a refactor to implement [Jetpack Compose](https://developer.android.com/jetpack/compose).
The idea is to segment this initial implementation in 5 parts.
1. Create new Composables replicating Fragment/Activity XML layouts;
2. Take an advantage of having MVP arch and pass Presenters functions to the composable (in order to follow [state hoisting principle](https://developer.android.com/jetpack/compose/state#state-hoisting));
3. Create data/state holder for holding a "temporary" UI State based on View Contracts to pass to the Compose, just for implementation purposes (we gonna refactor it later);
4. Use Compose [interoperable API](https://developer.android.com/jetpack/compose/interop/interop-apis#compose-in-fragments) and start removing Fragments XML layout; 
5. Finally starting refactoring architecture from MVP to MVVM+I (we need to discuss more about it) and replace the old logic.

After this, we'll be able to keep improving and adding more features with this new architecture.
This implementation is compatible with #42 

**Additional info**:
- [Heres a good quote about MVI](https://medium.com/swlh/mvi-architecture-with-android-fcde123e3c4a):
```
MVI is basically your favorite architecture (MVVM or MVP) with state management where there is only one state for all the app layers, a single-source of truth.
```
- [MVVM+I Example](https://github.com/k0siara/AndroidMVIExample/tree/master/app/src/main/java/com/patrykkosieradzki/androidmviexample/ui/features/add)

**Comment by Canato** [comment]
Perfect! but let's split this issue into small issues and do it.

Starting with point 1 `Create new Composables replicating Fragment/Activity XML layouts`
