### ISSUE TITLE
Jetpack Compose Implementation [Setup]

### ISSUE THREAD

**Issue by lucasvillaverde** [Canato/Purity-Test#63]
## Jetpack Compose Setup
- [Implementing library]( https://developer.android.com/jetpack/compose/interop/adding#anchor) in `home` feature module.
- Create first sample Composable Screen.

I would suggest create a project (Jetpack Compose Implementation) for the whole process. Does it make sense @Canato ?

**Comment by Canato** [comment]
Yeah, agreed

**Comment by lucasvillaverde** [comment]
Blocked by #66

**Comment by lucasvillaverde** [comment]
Solved by #68
